name: Rust Test

on:
  pull_request:
    # Only run it when Rust code changes
    paths:
      - 'src-tauri/**'

jobs:
  check:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: startsWith(matrix.platform, 'ubuntu-latest')
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-utils

      - name: Run tests
        working-directory: src-tauri
        run: |
          rustup component add rustfmt
          cargo check
          cargo clippy --all-targets --all-features
          cargo test --workspace -- --nocapture
